#Expyriment 0.10.0 (Python 3.7.16), .xpe-file, coding: cp1252
#date: Wed May 01 2024 12:22:41
#sha1: 4fc9f2
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Windows', node='T2', release='10', version='10.0.22621', machine='AMD64', processor='Intel64 Family 6 Model 122 Stepping 1, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
2080,design,log,
#design: #exp: Hsu task
#design: #dvn: Cue,SOA,target,key,response time
#design: block_cnt,block_id,trial_cnt,trial_id
2081,design,logged,
2081,Experiment,started
2081,stderr,received,'Traceback (most recent call last):'
2082,stderr,received,'  File "code.py", line 100, in <module>'
2083,stderr,received,'    key, rt = run_trial(cue_freq, SOA, target_freq)'
2083,stderr,received,'  File "code.py", line 81, in run_trial'
2085,stderr,received,'    expyriment.control.start(skip_ready_screen=True)'
2085,stderr,received,'  File "C:\\Users\\manon\\anaconda3\\envs\\expyriment\\lib\\site-packages\\expyriment\\control\\_experiment_control.py", line 73, in start'
2087,stderr,received,'    raise Exception("Experiment is already started!")'
2088,stderr,received,'Exception: Experiment is already started!'
