#Expyriment 0.10.0 (Python 3.7.16), .xpe-file, coding: cp1252
#date: Tue Apr 30 2024 09:44:06
#sha1: 576e47
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Windows', node='T2', release='10', version='10.0.22621', machine='AMD64', processor='Intel64 Family 6 Model 122 Stepping 1, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
1048,stdout,received,'0 0'
2065,design,log,
#design: #exp: Hsu task
#design: block_cnt,block_id,trial_cnt,trial_id
2065,design,logged,
2065,Experiment,started
2065,Stimulus,played,b'C:\\Users\\manon\\AppData\\Local\\Temp\\expyriment_4nj0wmkq\\freq1046_dur150.0_4obj71jg.wav'
3615,Stimulus,played,b'C:\\Users\\manon\\AppData\\Local\\Temp\\expyriment_4nj0wmkq\\freq1975_dur50.0_xrwu3bwi.wav'
3615,stdout,received,'0 1'
3644,stderr,received,'Traceback (most recent call last):'
3644,stderr,received,'  File "code.py", line 86, in <module>'
3645,stderr,received,'    run_trial(cue_freq, SOA, target_freq)'
3645,stderr,received,'  File "code.py", line 73, in run_trial'
3645,stderr,received,'    expyriment.control.start()'
3645,stderr,received,'  File "C:\\Users\\manon\\anaconda3\\envs\\expyriment\\lib\\site-packages\\expyriment\\control\\_experiment_control.py", line 73, in start'
3647,stderr,received,'    raise Exception("Experiment is already started!")'
3647,stderr,received,'Exception: Experiment is already started!'
