#Expyriment 0.10.0 (Python 3.7.16), .xpe-file, coding: cp1252
#date: Wed May 01 2024 12:30:21
#sha1: b84e03
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Windows', node='T2', release='10', version='10.0.22621', machine='AMD64', processor='Intel64 Family 6 Model 122 Stepping 1, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
446,design,log,
#design: #exp: Hsu task
#design: #dvn: Cue,SOA,target,key,response time
#design: block_cnt,block_id,trial_cnt,trial_id
446,design,logged,
446,Experiment,started
483,Stimulus,presented,0
512,Stimulus,presented,1
2275,Keyboard,received,32,wait
2276,Stimulus,played,b'C:\\Users\\manon\\AppData\\Local\\Temp\\expyriment_u7l3rgnj\\freq1318_dur150.0_p1t84asp.wav'
3526,Stimulus,played,b'C:\\Users\\manon\\AppData\\Local\\Temp\\expyriment_u7l3rgnj\\freq1975_dur50.0_4jrrbbnq.wav'
4939,Keyboard,received,32,wait
6189,stdout,received,'0 0'
6189,stderr,received,'Traceback (most recent call last):'
6189,stderr,received,'  File "code.py", line 101, in <module>'
6190,stderr,received,'    exp.data.add([cue_freq, SOA, target_freq, key, rt])'
6190,stderr,received,"NameError: name 'key' is not defined"
