#Expyriment 0.10.0 (Python 3.7.16), .xpe-file, coding: cp1252
#date: Tue Apr 30 2024 09:33:24
#sha1: 576e47
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Windows', node='T2', release='10', version='10.0.22621', machine='AMD64', processor='Intel64 Family 6 Model 122 Stepping 1, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
746,stdout,received,'0 0'
14318,design,log,
#design: #exp: Hsu task
#design: block_cnt,block_id,trial_cnt,trial_id
14319,design,logged,
14319,Experiment,started
14319,Stimulus,played,b'C:\\Users\\manon\\AppData\\Local\\Temp\\expyriment_qpyhmdi_\\freq1318_dur150.0__hqws9jf.wav'
15570,Stimulus,played,b'C:\\Users\\manon\\AppData\\Local\\Temp\\expyriment_qpyhmdi_\\freq1872_dur50.0__biyspzi.wav'
15570,stdout,received,'0 1'
15597,stderr,received,'Traceback (most recent call last):'
15597,stderr,received,'  File "code.py", line 86, in <module>'
15598,stderr,received,'    run_trial(cue_freq, SOA, target_freq)'
15598,stderr,received,'  File "code.py", line 73, in run_trial'
15599,stderr,received,'    expyriment.control.start()'
15599,stderr,received,'  File "C:\\Users\\manon\\anaconda3\\envs\\expyriment\\lib\\site-packages\\expyriment\\control\\_experiment_control.py", line 73, in start'
15602,stderr,received,'    raise Exception("Experiment is already started!")'
15603,stderr,received,'Exception: Experiment is already started!'
